version: '3.8'
services:
  weather:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    tty: true
    command: [ "python", "/app/src/run.py" ]
