version: '3.8'
services:
  weather:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    tty: true
    command: [ "python", "src/main.py" ]
  weather_test:
    build:
      context: .
    command: pytest
    volumes:
      - .:/app
