version: '3'
services:
  weather:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5000:5000"
    tty: true
    command: bash -c "python app.py"
